// `pnpm runtime` / `pnpm runtime:check`: the runtime modules as bytecode, embedded in the Kotlin library (docs/adr-006-hot-updates.md §2.11).
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { buildRuntime } from "../src/build.ts";

const [target, flag] = process.argv.slice(2);
if (!target || (flag !== undefined && flag !== "--check")) {
    process.stderr.write("usage: node scripts/runtime.ts <RuntimeBytecode.kt> [--check]\n");
    process.exit(2);
}

// a JVM class file holds a string constant of at most 65535 bytes
const CHUNK = 32_000;

const out = await mkdtemp(join(tmpdir(), "tinyui-runtime-"));
try {
    const modules = await buildRuntime({ root: join(import.meta.dirname, ".."), out });
    const fields: string[] = [];
    for (const m of modules) {
        const base64 = (await readFile(m.bin!)).toString("base64");
        const chunks = base64.match(new RegExp(`.{1,${CHUNK}}`, "g")) ?? [];
        const field = m.name.replace(/^tinyui-/, "");
        fields.push(`    val ${field}: Array<String> = arrayOf(\n${chunks.map((c) => `        "${c}",`).join("\n")}\n    )`);
    }
    const kt = `// Generated by \`pnpm runtime\` from packages/core and packages/native; do not edit.
package app.tinyui.generated

/** Base64 of the runtime modules' bytecode, split to fit JVM string constants. */
internal object RuntimeBytecode {
${fields.join("\n\n")}
}
`;
    if (flag === "--check") {
        const current = await readFile(target, "utf8").catch(() => "");
        if (current !== kt) {
            process.stderr.write(`${target} is out of date; run pnpm runtime\n`);
            process.exit(1);
        }
    } else {
        await writeFile(target, kt);
    }
} finally {
    await rm(out, { recursive: true, force: true });
}
