import type { ComponentDef, FieldDef, PropDef } from "./dsl.ts";
import { LAYOUT_PROPS } from "./dsl.ts";
import { COLOR_TOKENS, TEXT_STYLES } from "./tokens.ts";

const HEADER = "// Generated by `tinyui schema` from schema/; do not edit.";

/** [nodeImport] is where `Node` and `Ref` come from: `tinyui-core` for host packages, `../node.ts` inside core itself. */
export function generateTs(components: ComponentDef[], nodeImport = "tinyui-core"): string {
    const out: string[] = [HEADER];
    if (nodeImport === "tinyui-core") {
        out.push(`import type { ColorValue, Node, Ref } from "tinyui-core";`, "");
    } else {
        out.push(`import type { Node, Ref } from ${JSON.stringify(nodeImport)};`, "");
        out.push(`export type ColorToken = ${COLOR_TOKENS.map((t) => JSON.stringify(t)).join(" | ")};`);
        out.push("/** A literal `#RRGGBB` / `#AARRGGBB`, or a theme token resolved by the host at composition. */");
        out.push("export type ColorValue = `#${string}` | ColorToken;", "");
    }
    out.push("export interface LayoutProps {");
    for (const [k, p] of Object.entries(LAYOUT_PROPS)) out.push(`    ${k}?: ${tsPropType(p)};`);
    out.push("}", "");
    for (const c of components) {
        const id = tsIdent(c.name);
        for (const [ev, fields] of Object.entries(c.events)) out.push(...tsInterface(`${id}${cap(ev.slice(2))}Payload`, fields), "");
        for (const [cmd, fields] of Object.entries(c.commands)) out.push(...tsInterface(`${id}${cap(cmd)}Args`, fields), "");
        if (Object.keys(c.commands).length > 0) {
            out.push(`export type ${id}Commands = {`);
            for (const cmd of Object.keys(c.commands)) out.push(`    ${cmd}: ${id}${cap(cmd)}Args;`);
            out.push("};", "");
        }
        if (c.doc) out.push(`/** ${c.doc} */`);
        out.push(`export interface ${id}Props${c.layout ? " extends LayoutProps" : ""} {`);
        for (const [k, p] of Object.entries(c.props)) {
            if (p.doc) out.push(`    /** ${p.doc} */`);
            out.push(`    ${k}${p.required ? "" : "?"}: ${tsPropType(p)};`);
        }
        for (const ev of Object.keys(c.events)) out.push(`    ${ev}?: (e: ${id}${cap(ev.slice(2))}Payload) => void;`);
        if (Object.keys(c.commands).length > 0) out.push(`    ref?: Ref<${id}Commands>;`);
        if (c.children) out.push("    children?: Node | Node[];");
        out.push("}", "");
    }
    out.push("export interface IntrinsicElements {");
    for (const c of components) out.push(`    ${c.name.includes(".") ? JSON.stringify(c.name) : c.name}: ${tsIdent(c.name)}Props;`);
    out.push("}", "");
    for (const c of components) if (!c.name.includes(".")) out.push(`export const ${c.name} = ${JSON.stringify(c.name)};`);
    // host packages: one object per prefix so pages write <ta.Icon>, and the JSX namespace learns the tags
    const prefixed = components.filter((c) => c.name.includes("."));
    if (nodeImport === "tinyui-core" && prefixed.length > 0) {
        const byPrefix = new Map<string, ComponentDef[]>();
        for (const c of prefixed) { const [prefix] = c.name.split("."); byPrefix.set(prefix!, [...(byPrefix.get(prefix!) ?? []), c]); }
        for (const [prefix, cs] of byPrefix) out.push(`export const ${prefix} = { ${cs.map((c) => `${c.name.split(".")[1]}: ${JSON.stringify(c.name)}`).join(", ")} } as const;`);
        out.push("", `declare module "tinyui-core/jsx-runtime" {`, "    namespace JSX {", "        interface IntrinsicElements {");
        for (const c of prefixed) out.push(`            ${JSON.stringify(c.name)}: ${tsIdent(c.name)}Props;`);
        out.push("        }", "    }", "}");
    }
    return out.join("\n") + "\n";
}

export function generateKt(components: ComponentDef[], pkg: string, objectName: string): string {
    const out: string[] = [HEADER, `package ${pkg}`, "", "import app.tinyui.schema.ComponentSchema", "import app.tinyui.schema.FieldSpec", "import app.tinyui.schema.PropSpec", "", `object ${objectName} {`];
    for (const c of components) {
        out.push(`    val ${ktIdent(c.name)} = ComponentSchema(`);
        out.push(`        type = ${JSON.stringify(c.name)},`);
        out.push(`        props = mapOf(`);
        for (const [k, p] of Object.entries(c.props)) out.push(`            ${JSON.stringify(k)} to ${ktPropSpec(p)},`);
        out.push(`        ),`);
        out.push(`        events = mapOf(`);
        for (const [ev, fields] of Object.entries(c.events)) out.push(`            ${JSON.stringify(ev)} to ${ktFields(fields)},`);
        out.push(`        ),`);
        out.push(`        commands = mapOf(`);
        for (const [cmd, fields] of Object.entries(c.commands)) out.push(`            ${JSON.stringify(cmd)} to ${ktFields(fields)},`);
        out.push(`        ),`);
        out.push(`        children = ${c.children},`);
        out.push(`        layout = ${c.layout},`);
        out.push(`    )`, "");
    }
    out.push(`    val all: List<ComponentSchema> = listOf(${components.map((c) => ktIdent(c.name)).join(", ")})`);
    if (objectName === "BuiltinSchemas") {
        out.push("", "    /** Theme token names the schema DSL knows; Theme.kt must resolve each (checked by test). */");
        out.push(`    val colorTokens: Set<String> = setOf(${COLOR_TOKENS.map((t) => JSON.stringify(t)).join(", ")})`);
        out.push(`    val textStyles: Set<String> = setOf(${TEXT_STYLES.map((t) => JSON.stringify(t)).join(", ")})`);
    }
    out.push("}");
    return out.join("\n") + "\n";
}

function tsInterface(name: string, fields: Record<string, FieldDef>): string[] {
    const lines = [`export interface ${name} {`];
    for (const [k, f] of Object.entries(fields)) {
        if (f.doc) lines.push(`    /** ${f.doc} */`);
        lines.push(`    ${k}: ${f.kind};`);
    }
    lines.push("}");
    return lines;
}

function tsPropType(p: PropDef): string {
    switch (p.kind) {
        case "string": return "string";
        case "color": return "ColorValue";
        case "number": case "dp": case "sp": return "number";
        case "boolean": return "boolean";
        case "size": return 'number | "fill" | "wrap"';
        case "icon": return "string";
        case "enum": return (p.values ?? []).map((v) => JSON.stringify(v)).join(" | ");
    }
}

function ktPropSpec(p: PropDef): string {
    const flags = `required = ${!!p.required}, initial = ${!!p.initial}`;
    const d = p.default;
    switch (p.kind) {
        case "string": return `PropSpec.Str(default = ${d === undefined ? "null" : JSON.stringify(d)}, ${flags})`;
        case "number": return `PropSpec.Num(default = ${ktDouble(d)}, ${flags})`;
        case "boolean": return `PropSpec.Bool(default = ${d === undefined ? "null" : `${d}`}, ${flags})`;
        case "dp": return `PropSpec.Dp(default = ${ktDouble(d)}, ${flags})`;
        case "sp": return `PropSpec.Sp(default = ${ktDouble(d)}, ${flags})`;
        case "color": return `PropSpec.ColorSpec(default = ${d === undefined ? "null" : JSON.stringify(d)}, ${flags})`;
        case "size": return `PropSpec.Size(default = ${d === undefined ? "null" : JSON.stringify(String(d))}, ${flags})`;
        case "icon": return `PropSpec.IconSpec(${flags})`;
        case "enum": return `PropSpec.Enum(values = setOf(${(p.values ?? []).map((v) => JSON.stringify(v)).join(", ")}), default = ${d === undefined ? "null" : JSON.stringify(d)}, ${flags})`;
    }
}

function ktFields(fields: Record<string, FieldDef>): string {
    const entries = Object.entries(fields).map(([k, f]) => `${JSON.stringify(k)} to FieldSpec.${cap(f.kind === "boolean" ? "Bool" : f.kind === "number" ? "Num" : "Str")}`);
    return entries.length === 0 ? "emptyMap()" : `mapOf(${entries.join(", ")})`;
}

const ktDouble = (d: string | number | boolean | undefined) => (d === undefined ? "null" : Number.isInteger(Number(d)) ? `${Number(d)}.0` : `${Number(d)}`);
const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
export const identOf = (name: string) => name.split(".").map(cap).join("");
const tsIdent = identOf;
const ktIdent = identOf;
